config/routes.rb
ActressApp::Application.routes.draw do
  resources :tumblr_users

  get '/tag/:id' => 'tags#show', as: :tag
  resources :tags , except: [:show]

  resources :photos

  get '/actress/:id' => 'actresses#show', as: :actress
  patch '/actress/:id' => 'actresses#update'
  put '/actress/:id' => 'actresses#update'
  get '/actresses/parts_random' => 'actresses#parts_random'
  get '/actresses/parts_indivisual' => 'actresses#parts_indivisual'
  resources :actresses , except: [:show,:update]

  root :to=>"actresses#index_photos"

  get '/sitemap' => 'sitemap#index'

  get '/actress/image/:a_id/:p_id' => 'photos#photo', as: :actress_photo

  get '/admi' => 'admin#index', as: :admin

  post '/regist_similar' => 'admin#regist_similar'
  post '/regist_tag' => 'admin#regist_tag'

  post "regist/photo" => 'regist#photo', as: :regist_photo
  get "regist/form" => 'regist#form', as: :regist_form

  

end

app/controllers/actresses_controller.rb
# coding: utf-8
class ActressesController < ApplicationController
  protect_from_forgery except: [:parts_random, :parts_indivisual]
  before_action :authenticate, only: [:index,:new,:edit,:create,:update,:destroy]
  before_action :set_tags, only: [:index_photos,:show]
  before_action :set_actresses, only: [:index_photos,:show, :parts_random]
  before_action :set_actress, only: [:show,:edit, :update, :destroy]

  # GET /actresses
  def index
    @actresses = Actress.all
  end

  def index_photos
  end

  def parts_random
    respond_to do |format|
      format.js { render }
    end
  end

  def parts_indivisual
    respond_to do |format|
      format.js { render }
    end
  end

  def show
    render status: :not_found, file: "#{Rails.root}/public/404.html" and return if !@actress
    #301
    redirect_to @actress,status: 301 and return if params[:page] == "0" 
    #302
    redirect_to @actress and return if !params[:page].nil? && !params[:page].to_i.between?(1,@actress.page_size-1)
    @title = "#{@actress.name}の画像 全#{@actress.photos.released.size.to_s}枚#{params[:page].to_i+1}ページ目"
  end

  # GET /actresses/new
  def new
    @actress = Actress.new
  end

  # GET /actresses/1/edit
  def edit
  end

  # POST /actresses
  def create
    @actress = Actress.new(actress_params)

    respond_to do |format|
      if @actress.save
        format.html { redirect_to @actress, notice: 'Actress was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /actresses/1
  def update
    respond_to do |format|
      if @actress.update(actress_params)
        format.html { redirect_to @actress, notice: 'Actress was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /actresses/1
  def destroy
    @actress.destroy
    respond_to do |format|
      format.html { redirect_to actresses_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actress
      @actress = Actress.find(params[:id])
    end

    def set_actresses
      @actresses = Actress.display.released.to_a
      @picked = Actress.all.picked
    end

    def set_tags
      @tags = Tag.all
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def actress_params
      params.require(:actress).permit(:name, :text, :display, :pick_up)
    end
end

app/helpers/actresses_helper.rb
module ActressesHelper
end

app/views/actresses/_actress_list.html.haml
-# coding: utf-8
- if @actress && !@actress.similars.empty?
  %h3 
    = "#{@actress.name} に似ている女優"
  - @actress.similars = @actress.similars.sort_by{rand}
  -# トップページなら全部、それ以外なら6個
  - @lis = request.path=="/" ? 6  : 2
  - @uls = request.path=="/" ? @actress.similars.size / 6  : 1
  - @uls.times do |i|
    %ul.thumbnails
      - (i*@lis).upto(i*@lis+@lis-1) do |n|
        - actress = @actress.similars[n]
        - if actress
          %li.span2
            = link_to actress,class: :thumnail do
              %img{:src=>"#{actress.thumbnail_rand}",:onerror=>"this.src='/assets/no_image.gif';this.width='128';this.height='128';this.style.left=0;",:style=>"left:0px;",:alt=>"#{actress.name}",:title=>"#{actress.name}"}
            = link_to actress do
              = actress.name + " #{actress.photos.size.to_s}枚"

- if request.path=="/" 
  = render :partial => "what_new"
 

- if request.path=="/" 
  %h3 おすすめ女優
- else
  %h3 ピックアップ
- @actresses = @actresses.sort_by{rand} if @actresses
-# トップページなら全部、それ以外なら6個
- @lis = request.path=="/" ? 6  : 2
-# @uls = request.path=="/" ? @actresses.size / (params["full"] ? 6 : 18)  : 1
- @uls = 1
- @uls.times do |i|
  %ul.thumbnails
    - (i*@lis).upto(i*@lis+@lis-1) do |n|
      - actress = @picked[n] if @picked
      - if actress
        %li.span2
          = link_to actress,class: :thumnail do
            %img{:src=>"#{actress.thumbnail_rand}",:onerror=>"this.src='/assets/no_image.gif';this.width='128';this.height='128';this.style.left=0;",:style=>"left:0px;",:alt=>"#{actress.name}",:title=>"#{actress.name}"}
          = link_to actress do
            = actress.name + " #{actress.photos.size.to_s}枚"

- if request.path=="/" 
  = render :partial => "button_list"

app/views/actresses/_form.html.haml
= form_for @actress do |f|
  - if @actress.errors.any?
    #error_explanation
      %h2= "#{pluralize(@actress.errors.count, "error")} prohibited this actress from being saved:"
      %ul
        - @actress.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :pick_up
    = f.number_field :pick_up
  .field
    = f.label :display
    = f.check_box :display
  .actions
    = f.submit 'Save'

app/views/actresses/_indivisual.js.haml
- actress = Actress.where(name: params[:actress]).first
%div
  - actress.photos.sort_by{rand}.each_with_index do |photo,index2|
    - if index2 < 4
      %span
        = link_to actress_photo_url(actress,photo),target: :blank do
          %img{:src=>photo.url,:alt=>"#{actress.name}",:width=>"100%"}
        %br
        = link_to actress_url(actress),target: :blank do
          = "#{actress.name} #{actress.photos.size}枚"
        %br
%h2
  %u
    = link_to actress_url(actress),target: :blank do
      = "#{actress.name} 画像#{actress.photos.size}枚"

app/views/actresses/_paginate.html.haml
-# paginate
%ul.pager
  - page = params[:page].to_i
  %li{:class=>("disabled" if page.zero? )}
    - if page.zero?
    - else
      = link_to actress_path(@actress,page:"#{page-1}") do
        　前へ　

  %li{:class=>("disabled" if page.zero? )}
    = "#{page+1} / #{@actress.page_size.to_s}ページ"

  %li{:class=>("disabled" if @actress.page_size - 1 == page )}
    - if @actress.page_size - 1 == page
    - else 
      = link_to actress_path(@actress,page:"#{page+1}") do
        　次へ　

app/views/actresses/_parts.js.haml
- @actresses.sort_by{rand}.each_with_index do |actress,index|
  - if index < 15
    %span
      - actress.photos.sort_by{rand}.each_with_index do |photo,index2|
        - if index2 < 2
          %span
            = link_to actress_photo_url(actress,photo),target: :blank do
              %img{:src=>photo.url,:alt=>"#{actress.name}",:width=>"100%"}
            = link_to actress_url(actress),target: :blank do
              = "#{actress.name} #{actress.photos.size}枚"
              %br

app/views/actresses/_random.js.haml
-# all actresses
- @actresses.sort_by{rand}.each_with_index do |actress,index|
  - if index < 15
    %span
      - actress.photos.sort_by{rand}.each_with_index do |photo,index2|
        - if index2 < 2
          %span
            = link_to actress_photo_url(actress,photo),target: :blank do
              %img{:src=>photo.url,:alt=>"#{actress.name}",:width=>"100%"}
            = link_to actress_url(actress),target: :blank do
              = "#{actress.name} #{actress.photos.size}枚"
              %br

app/views/actresses/_tag_list.html.haml
-# coding: utf-8
%h3 全てのジャンル

%p

- if @tags
  - @tags.each do |tag|
    = link_to tag do
      %button{:class=>"btn",:type=>"submit"}
        = "#{tag.name}"
%p

app/views/actresses/_what_new.html.haml
:javascript
  var blogroll_channel_id = 106008;
%script{type: "text/javascript",charset: "utf-8",src: "http://blogroll.livedoor.net/js/blogroll.js"}
%link{rel: "stylesheet",type: "text/css",href: "http://blogroll.livedoor.net/css/default2.css"}

.span12
  %div{:class=>"well sidebar-nav"}
    %ul{:class=>"nav nav-list"}
      - Photo.table(:latest).sort_by{|t|t[:date]}.reverse.each do |t|
        - day = Time.parse(t[:date]) + (60*60*9) #tokyo
        %li
          = link_to actress_path(t[:name]) do
            %u
              = "#{day.month}/#{day.day}"
              = "「#{t[:name]}」#{t[:size]}枚追加！"

app/views/actresses/admin.html.haml
-# coding: utf-8
%h1 admin

-# similar-regist
[similar]
= form_tag "/regist_similar" do
  %dt
    form
    %dd
      お名前
      %select{:name=>"name"}
        - @actresses.each do |a|
          %option{:value=>a.name.to_s}= a.name.to_s + (a.display ? "★" : "☆")
    - (101..105).each do |i|
      %dd
        - d = "act" + i.to_s[1,2]
        = d
        %select{:name=> d }
          %option{:value=>""}= ""
          - @actresses.each do |a|
            %option{:value=>a.name.to_s}= a.name.to_s + (a.display ? "★" : "☆")
  %button{:type=>"submit"} submit

%br
-# tag-regist
[tag]
= form_tag "/regist_tag" do
  %dt
    form
    %dd
      タグ名
      %select{:name=>"name"}
        - @tags.each do |tag|
          %option{:value=>tag.name.to_s}= tag.name.to_s
    - (101..105).each do |i|
      %dd
        - d = "act" + i.to_s[1,2]
        = d
        %select{:name=> d }
          %option{:value=>""}= ""
          - @actresses.each do |a|
            %option{:value=>a.name.to_s}= a.name.to_s + (a.display ? "★" : "☆")
  %button{:type=>"submit"} submit


[予約配信状況]
%p
  = "未配信:#{@unreleased.size}"
%p
  = "配信済:#{@released.size}"

[直近5日以内配信]
%table
  %tr
    %th Name
    %th Date
    %th Size
  - Photo.table(:latest).sort_by{|t|t[:date]}.reverse.each do |t|
    %tr
      %td= t[:name]
      %td= Time.parse(t[:date]) + 60*60*9 #tokyo
      %td= t[:size]
%br
[未配信]
%table
  %tr
    %th Name
    %th Date
    %th Size
  - Photo.table(:unreleased).sort_by{|t|t[:date]}.reverse.each do |t|
    %tr
      %td= t[:name]
      %td= Time.parse(t[:date]) + 60*60*9 #tokyo
      %td= t[:size]
%br

app/views/actresses/index.html.haml
%h1 Listing actresses

%table
  %tr
    %th Name
    %th Text
    %th PickUp
    %th Display
    %th
    %th
    %th

  - @actresses.each do |actress|
    %tr
      %td= actress.name
      %td= actress.text
      %td= actress.pick_up
      %td= actress.display
      %td= link_to 'Show', actress
      %td= link_to 'Edit', edit_actress_path(actress)
      %td= link_to 'Destroy', actress, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Actress', new_actress_path

app/views/actresses/index_photos.html.haml
= render :partial => 'actress_list'

app/views/actresses/parts_indivisual.js.haml
= raw('var content=".article-body-inner"; if(jQuery(content).html() == undefined){content = ".article-body";}; jQuery(content).append("' + (render partial: "indivisual").gsub(/"/,"\\\"").gsub("\n","") + '");')

app/views/actresses/parts_random.html.haml
- @actresses.sort_by{rand}.each_with_index do |actress,index|
  - if index < 10
    %span
      = link_to actress_url(actress),target: :blank do
        = "#{actress.name} #{actress.photos.size}枚"
      - actress.photos.sort_by{rand}.each_with_index do |photo,index2|
        - if index2 < 10
          %span
            = link_to actress_photo_url(actress,photo),target: :blank do
              %img{:src=>photo.url,:alt=>"#{actress.name}",:width=>"100%"}
            = link_to actress_url(actress),target: :blank do
              = "#{actress.name}"
        %p

app/views/actresses/parts_random.js.haml
= raw('document.write("' + (render partial: "random").gsub(/"/,"\\\"").gsub("\n","") + '");')