config/routes.rb
ActressApp::Application.routes.draw do
  resources :tumblr_users

  get '/tag/:id' => 'tags#show', as: :tag
  resources :tags , except: [:show]

  resources :photos

  get '/actress/:id' => 'actresses#show', as: :actress
  patch '/actress/:id' => 'actresses#update'
  put '/actress/:id' => 'actresses#update'
  get '/actresses/parts_random' => 'actresses#parts_random'
  get '/actresses/parts_indivisual' => 'actresses#parts_indivisual'
  resources :actresses , except: [:show,:update]

  root :to=>"actresses#index_photos"

  get '/sitemap' => 'sitemap#index'

  get '/actress/image/:a_id/:p_id' => 'photos#photo', as: :actress_photo

  get '/admi' => 'admin#index', as: :admin

  post '/regist_similar' => 'admin#regist_similar'
  post '/regist_tag' => 'admin#regist_tag'

  post "regist/photo" => 'regist#photo', as: :regist_photo
  get "regist/form" => 'regist#form', as: :regist_form

  

end

app/models/tag.rb
# coding: utf-8
require 'mongoid' 
class Tag
  include Mongoid::Document
  field :name, type: String
  validates :name, uniqueness: true
  field :_id, type: String, default: ->{ name }
  
  field :text, type: String
  has_and_belongs_to_many :actresses
  def photos
    actresses.to_a.map{|a|a.photos.released}.flatten
  end

  def photos_sort_by_points
    photos.sort_by{|p|p.point}.reverse
  end

  def page_size
    (photos.size.to_f / 8 ).ceil
  end

end

app/controllers/tags_controller.rb
# coding:utf-8
class TagsController < ApplicationController
  before_action :authenticate, only: [:index,:new,:edit,:create,:update,:destroy]
  before_action :set_tag, only: [:edit, :update, :destroy]

  def show
    @actresses = Actress.display.released.to_a
    @tag = Tag.find(params[:id])
    render status: :not_found, file: "#{Rails.root}/public/404.html" and return if !@tag
    @tags = Tag.all
    redirect_to @tag if !params[:page].nil? && !params[:page].to_i.between?(1,@tag.page_size-1)
    @title = "#{@tag.name}の画像 全#{@tag.photos.size.to_s}枚#{params[:page].to_i+1}ページ目"
  end

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:id,:name,:text)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/tags/_paginate.html.haml
-# paginate
%ul.pager
  - page = params[:page].to_i
  %li{:class=>("disabled" if page.zero? )}
    - if page.zero?
    - else
      = link_to tag_path(@tag,page: "#{page-1}") do
        　前へ　

  %li{:class=>("disabled" if page.zero? )}
    = "#{page+1} / #{@tag.page_size.to_s}ページ"

  %li{:class=>("disabled" if @tag.page_size - 1 == page )}
    - if @tag.page_size - 1 == page
    - else 
      = link_to tag_path(@tag,page: "#{page+1}") do
        　次へ　

app/views/tags/edit.html.haml
%h1 Editing tag

= render 'form'

= link_to 'Show', @tag
\|
= link_to 'Back', tags_path

app/views/tags/index.html.haml
%h1 Listing tags

%table
  %tr
    %th Name
    %th Text
    %th
    %th
    %th

  - @tags.each do |tag|
    %tr
      %td= tag.name
      %td= tag.text
      %td= link_to 'Show', tag
      %td= link_to 'Edit', edit_tag_path(tag)
      %td= link_to 'Destroy', tag, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.haml
-#nend
:javascript
  var nend_params = {"media":9374,"site":38951,"spot":79043,"type":1,"oriented":1};
%script{:type=>"text/javascript",:src=>"http://js1.nend.net/js/nendAdLoader.js"}


%h2{:itemprop=>"name"}
  ="#{@tag.name}の画像" if @tag

-# social feedback
- require 'uri'
- if params[:page].to_i.zero?
  %a{:href=>"https://twitter.com/share",:class=>"twitter-share-button",:"data-count"=>"horizontal",:"data-url"=>"#{request.url}",:"data-text"=>"#{@title}",:"data-lang"=>"ja"}
    Tweet
  %script{:charset=>"utf-8",:type=>"text/javascript",:src=>"//platform.twitter.com/widgets.js"}
  %a{:href=>"http://b.hatena.ne.jp/entry/#{request.url}",:class=>"hatena-bookmark-button",:"data-hatena-bookmark-title"=>"#{@title}",:"data-hatena-bookmark-layout"=>"standard",:title=>"このエントリーをはてなブックマークに追加"}
    %img{:src=>"http://b.st-hatena.com/images/entry-button/button-only.gif",:alt=>"このエントリーをはてなブックマークに追加",:width=>"20",:height=>"20",:style=>"border: none;"} 
  %script{:type=>"text/javascript",:src=>"http://b.st-hatena.com/js/bookmark_button.js",:charset=>"utf-8",:async=>"async"}
  %iframe{:src=>"//www.facebook.com/plugins/like.php?href=#{URI.encode request.url}&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;font=arial&amp;colorscheme=light&amp;action=like&amp;height=21&amp;appId=283852644973946",:scrolling=>"no",:frameborder=>"0",:style=>"border:none; overflow:hidden; width:450px; height:21px;",:allowTransparency=>"true"}


-# text
- if params[:page].to_i.zero?
  .well
    %p{:itemprop=>"articleBody"}
      = raw @tag.text


-# photos
.container-fluid
  .row-fluid
    - (params[:page].to_i*8).upto((params[:page].to_i*8) +8 - 1) do |i|
      - if photo = @tag.photos_sort_by_points[i]
        .span5
          = link_to actress_photo_path(photo.actress,photo),target: :blank do
            - if i == 0
              %img{:src=>photo.url,:alt=>"#{@tag.name},#{photo.actress.name}",:width=>"40%",:itemprop=>"image"}
            - if i >= 1
              %img{:src=>photo.url,:alt=>"#{@tag.name},#{photo.actress.name}",:width=>"40%"}
          %button{:class=>"btn",:type=>"button"}
            = link_to photo.actress do
              = photo.actress.name
          %p


-# paginate
= render :partial => "paginate"

:javascript
  var nend_params = {"media":9374,"site":38951,"spot":76150,"type":1,"oriented":1};
%script{:type=>"text/javascript",:src=>"http://js1.nend.net/js/nendAdLoader.js"}

-# actress list
.well
  = render :partial => "actresses/actress_list"

-# paginate
= render :partial => "paginate"

-# button_list
= render :partial => "actresses/button_list"

-# tag_list
= render :partial => "actresses/tag_list"

= content_for :title do
  = @title
= content_for :url_content do
  = "http://xn--o1q8h80u333a.xn--u9jw89o.com/tag/#{@tag.name}"
-# TODO Tag#release_date
-#= content_for :datePublished do
  = @tag.release_date.to_s[0,10] 

- if !params[:page].to_i.zero?
  = content_for :link_rel_prev do
    = "/tag/#{@tag.name}/?page=#{params[:page].to_i - 1}"
- if @tag.page_size - 1 > params[:page].to_i
  = content_for :link_rel_next do
    = "/tag/#{@tag.name}/?page=#{params[:page].to_i + 1}"