config/routes.rb
ActressApp::Application.routes.draw do
  resources :tumblr_users

  get '/tag/:id' => 'tags#show', as: :tag
  resources :tags , except: [:show]

  resources :photos

  get '/actress/:id' => 'actresses#show', as: :actress
  patch '/actress/:id' => 'actresses#update'
  put '/actress/:id' => 'actresses#update'
  get '/actresses/parts_random' => 'actresses#parts_random'
  get '/actresses/parts_indivisual' => 'actresses#parts_indivisual'
  resources :actresses , except: [:show,:update]

  root :to=>"actresses#index_photos"

  get '/sitemap' => 'sitemap#index'

  get '/actress/image/:a_id/:p_id' => 'photos#photo', as: :actress_photo

  get '/admi' => 'admin#index', as: :admin

  post '/regist_similar' => 'admin#regist_similar'
  post '/regist_tag' => 'admin#regist_tag'

  post "regist/photo" => 'regist#photo', as: :regist_photo
  get "regist/form" => 'regist#form', as: :regist_form

  

end

app/models/photo.rb
# coding: utf-8
class Photo
  include Mongoid::Document
  field :path, type: String
  field :url, type: String
  field :secure_url, type: String
  field :big_url, type: String
  belongs_to :actress, class_name: 'Actress'
  field :release_date, type: Time
  field :point, type: Integer, default: 0

  scope :released   , ->{where(:release_date.lte => Time.zone.now)}
  scope :unreleased , ->{where(:release_date.gt  => Time.zone.now)}

  index({ point: 1 }, { name: "point_index" })

  # 5days latest
  scope :latest , ->{between(release_date: ((Time.now-60*60*24*5)..(Time.now)))}

  def index
    actress.photos_sort_by_points.index(self)
  end

  def actress_photos_size
    actress.photos.released.size
  end

  def self.table(sym=:latest)
    self.group(sym).map{|k,v|{:name=>k[0].name,:date=>k[1].to_s,:size=>v.size}}
  end

  private
  def self.group(sym)
    self.send(sym).group_by{|p| [p.actress,p.release_date]}
  end

end

app/controllers/photos_controller.rb
# coding: utf-8
class PhotosController < ApplicationController
  before_action :authenticate, only: [:index,:new,:edit,:create,:update,:destroy]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]


  def photo
    @tags      = Tag.all
    @actresses = Actress.display.released.to_a
    @picked    = Actress.picked
    @actress   = Actress.find(params[:a_id])
    @photo     = Photo.find(params[:p_id])
    render status: :not_found, file: "#{Rails.root}/public/404.html" and return if !@photo
    @title = "#{@photo.actress.name}の画像 全#{@photo.actress.photos.released.size.to_s}枚 No.#{@photo.actress.photos_sort_by_release_date.index(@photo)+1}"
    if Rails.env.development?
      @photo.point += 1
      @photo.save
    end
  end

  # GET /photos
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /photos/1
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /photos/1
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:path, :url, :secure_url)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for @photo do |f|
  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :secure_url
    = f.text_field :secure_url
  .actions
    = f.submit 'Save'

app/views/photos/_paginate.html.haml
-# paginate
%ul.pager
  %li{:class=>("disabled" if @photo.index.zero? )}
    - if @photo.index.zero?
    - else
      = link_to actress_photo_path(@photo.actress,@photo.actress.photos_sort_by_points[@photo.index-1].id) do
        　前へ　

  %li{:class=>("disabled")}
    = "#{@photo.actress.name} 人気順 #{@photo.index+1} / #{@photo.actress_photos_size}枚目"

  %li{:class=>("disabled" if @photo.actress_photos_size - 1 == @photo.index )}
    - if @photo.actress_photos_size - 1 == @photo.index
    - else 
      = link_to actress_photo_path(@photo.actress,@photo.actress.photos_sort_by_points[@photo.index+1].id) do
        　次へ　

%p
  = link_to actress_path(@photo.actress,page: "#{(@photo.index.to_f/8).to_i}") do
    %button{:class=>"btn",:type=>"submit"}
      = "#{@photo.actress.name} の画像一覧"
%p

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
%h1 Listing photos

%table
  %tr
    %th Path
    %th Url
    %th Secure url
    %th Release date
    %th
    %th
    %th

  - @photos.each do |photo|
    %tr
      %td= photo.path
      %td= photo.url
      %td= photo.secure_url
      %td= photo.release_date
      %td= link_to 'Show', photo
      %td= link_to 'Edit', edit_photo_path(photo)
      %td= link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Photo', new_photo_path

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/photo.html.haml
-# coding: utf-8
%p
  = link_to actress_path(@photo.actress,page: "#{(@photo.index.to_f/8).to_i}") do
    %button{:class=>"btn",:type=>"submit"}
      = "#{@photo.actress.name} の画像一覧"

%h2="#{@photo.actress.name}の画像" if @photo.actress

-# photos
.container-fluid
  .row-fluid
    .li.span12
      %img{:src=>@photo.big_url}

= render :partial => "paginate"

-# actress list
.well
  -#= render :partial => "actresses/actress_list"
= content_for :title do
  = @title

-#= render :partial => "actresses/button_list"

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Path:
  = @photo.path
%p
  %b Url:
  = @photo.url
%p
  %b Secure url:
  = @photo.secure_url

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path

app/views/photos/show_a_photo.html.haml
-# coding: utf-8
- photo_index = @photo.actress.photos_sort_by_points.index(@photo)
%p
  = link_to actress_path(@photo.actress,page: "#{(photo_index.to_f/8).to_i}") do
    %button{:class=>"btn",:type=>"submit"}
      = "#{@photo.actress.name} の画像一覧"

%h2="#{@photo.actress.name}の画像" if @photo.actress

-# photos
.container-fluid
  .row-fluid
    .li.span12
      %img{:src=>@photo.big_url}

= render :partial => "paginate"

-# actress list
.well
  = render :partial => "actresses/actress_list"
= content_for :title do
  = @title

= render :partial => "actresses/button_list"