config/routes.rb
ActressApp::Application.routes.draw do
  resources :tumblr_users

  get '/tag/:id' => 'tags#show', as: :tag
  resources :tags , except: [:show]

  resources :photos

  get '/actress/:id' => 'actresses#show', as: :actress
  patch '/actress/:id' => 'actresses#update'
  put '/actress/:id' => 'actresses#update'
  get '/actresses/parts_random' => 'actresses#parts_random'
  get '/actresses/parts_indivisual' => 'actresses#parts_indivisual'
  resources :actresses , except: [:show,:update]

  root :to=>"actresses#index_photos"

  get '/sitemap' => 'sitemap#index'

  get '/actress/image/:a_id/:p_id' => 'photos#photo', as: :actress_photo

  get '/admi' => 'admin#index', as: :admin

  post '/regist_similar' => 'admin#regist_similar'
  post '/regist_tag' => 'admin#regist_tag'

  post "regist/photo" => 'regist#photo', as: :regist_photo
  get "regist/form" => 'regist#form', as: :regist_form

  

end

app/models/tumblr_user.rb
require 'tumblife'
class TumblrUser
  include Mongoid::Document
  field :host, type: String
  field :consumer_key, type: String
  field :consumer_secret, type: String
  field :memo
  field :oauth_token, type: String
  field :oauth_token_secret, type: String
  field :spend, type: Integer, default: 0
  field :last_spend, type: Time, default: Time.mktime(2012,6,1)
  DailyMax  = 75
  ResetHour = 16

  def upload(uri)
    mash = ::Tumblife.client.photo("#{self.host}.tumblr.com",source: uri)
    self.spend += 1
    self.last_spend = Time.zone.now
    self.save
    mash.id 
  end

  def self.attend
    self.update
    attendee = self.all.select{|u|!u.max?}.sort_by{|u|u.last_spend}.reverse.first 
    raise "no man can upload(daily limit)" if !attendee
    attendee.tumblife_configure
  end

  def resetable?
    return true if !last_spend
    if last_spend.hour < ResetHour
      reset_time = last_spend.to_date.to_time + ResetHour*60*60
    else
      reset_time = last_spend.to_date.next_day.to_time + ResetHour*60*60
    end
    Time.zone.now > reset_time
  end

  def reset
    spend = 0
    last_spend = Time.zone.now
    save
  end

  def max?
    spend >= DailyMax
  end

  def tumblife_configure
    Tumblife.configure do |config|
      config.consumer_key       = self.consumer_key
      config.consumer_secret    = self.consumer_secret
      config.oauth_token        = self.oauth_token
      config.oauth_token_secret = self.oauth_token_secret
    end
    self
  end

  private

  def self.update
    self.all.each do |u|
      u.reset if u.resetable?
    end
  end

end

app/controllers/tumblr_users_controller.rb
class TumblrUsersController < ApplicationController
  before_action :authenticate
  before_action :set_tumblr_user, only: [:show, :edit, :update, :destroy]

  # GET /tumblr_users
  # GET /tumblr_users.json
  def index
    @tumblr_users = TumblrUser.all
  end

  # GET /tumblr_users/1
  # GET /tumblr_users/1.json
  def show
  end

  # GET /tumblr_users/new
  def new
    @tumblr_user = TumblrUser.new
  end

  # GET /tumblr_users/1/edit
  def edit
  end

  # POST /tumblr_users
  # POST /tumblr_users.json
  def create
    @tumblr_user = TumblrUser.new(tumblr_user_params)

    respond_to do |format|
      if @tumblr_user.save
        format.html { redirect_to @tumblr_user, notice: 'Tumblr user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tumblr_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @tumblr_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tumblr_users/1
  # PATCH/PUT /tumblr_users/1.json
  def update
    respond_to do |format|
      if @tumblr_user.update(tumblr_user_params)
        format.html { redirect_to @tumblr_user, notice: 'Tumblr user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tumblr_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tumblr_users/1
  # DELETE /tumblr_users/1.json
  def destroy
    @tumblr_user.destroy
    respond_to do |format|
      format.html { redirect_to tumblr_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tumblr_user
      @tumblr_user = TumblrUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tumblr_user_params
      params.require(:tumblr_user).permit(:host, :consumer_key, :consumer_secret, :oauth_token, :oauth_token_secret, :spend, :last_spend, :memo)
    end

end

app/helpers/tumblr_users_helper.rb
module TumblrUsersHelper
end

app/views/tumblr_users/_form.html.haml
= form_for @tumblr_user do |f|
  - if @tumblr_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tumblr_user.errors.count, "error")} prohibited this tumblr_user from being saved:"
      %ul
        - @tumblr_user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :host
    = f.text_field :host
  .field
    = f.label :consumer_key
    = f.text_field :consumer_key
  .field
    = f.label :consumer_secret
    = f.text_field :consumer_secret
  .field
    = f.label :oauth_token
    = f.text_field :oauth_token
  .field
    = f.label :oauth_token_secret
    = f.text_field :oauth_token_secret
  .field
    = f.label :memo
    = f.text_area :memo
  .field
    = f.label :spend
    = f.number_field :spend
  .field
    = f.label :last_spend
    = f.text_field :last_spend
  .actions
    = f.submit 'Save'

app/views/tumblr_users/edit.html.haml
%h1 Editing tumblr_user

= render 'form'

= link_to 'Show', @tumblr_user
\|
= link_to 'Back', tumblr_users_path

app/views/tumblr_users/index.html.haml
%h1 Listing tumblr_users

%table
  %tr
    %th Host
    %th Consumer key
    -#%th Consumer secret
    %th Memo
    -#%th Oauth token
    -#%th Oauth token secret
    %th Spend
    %th Last spend
    %th
    %th
    %th

  - @tumblr_users.each do |tumblr_user|
    %tr
      %td= tumblr_user.host
      %td= tumblr_user.consumer_key
      -#%td= tumblr_user.consumer_secret
      %td
        %p
          = raw(tumblr_user.memo.to_s.split(/\r/).join("<br>"))
      -#%td= tumblr_user.oauth_token
      -#%td= tumblr_user.oauth_token_secret
      %td= tumblr_user.spend
      %td= tumblr_user.last_spend
      %td= link_to 'Show', tumblr_user
      %td= link_to 'Edit', edit_tumblr_user_path(tumblr_user)
      %td= link_to 'Destroy', tumblr_user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tumblr user', new_tumblr_user_path

app/views/tumblr_users/new.html.haml
%h1 New tumblr_user

= render 'form'

= link_to 'Back', tumblr_users_path

app/views/tumblr_users/show.html.haml
%p#notice= notice

%p
  %b Host:
  = @tumblr_user.host
%p
  %b Consumer key:
  = @tumblr_user.consumer_key
%p
  %b Consumer secret:
  = @tumblr_user.consumer_secret
%p
  %b Oauth token:
  = @tumblr_user.oauth_token
%p
  %b Oauth token secret:
  = @tumblr_user.oauth_token_secret
%p
  %b Memo:
  = @tumblr_user.memo
%p
  %b Spend:
  = @tumblr_user.spend
%p
  %b Last spend:
  = @tumblr_user.last_spend

= link_to 'Edit', edit_tumblr_user_path(@tumblr_user)
\|
= link_to 'Back', tumblr_users_path